---
title: "Sleep"
output: html_document
---

```{r setup}
library(dplyr)
library(ggplot2)
library(lubridate)
library(XML)

#load apple health export.xml file
  xml <- xmlParse("data/20170416.xml")

#transform xml file to data frame - select the Record rows from the xml file
  df <- XML:::xmlAttrsToDataFrame(xml["//Record"])

#make value variable numeric
  df$value <- as.numeric(as.character(df$value))

#make endDate in a date time variable POSIXct using lubridate with eastern time zone
  df$startDate_full <-ymd_hms(df$startDate)
  df$endDate_full <-ymd_hms(df$endDate)

##add in year month date dayofweek hour columns
  df$endMonth<-format(df$endDate_full,"%m")
  df$endYear<-format(df$endDate_full,"%Y")
  df$endDate<- as.Date(format(df$endDate_full,"%Y-%m-%d"))
  df$endDayofweek <-wday(df$endDate_full, label=TRUE, abbr=FALSE)
  df$endHour <-format(df$endDate_full,"%H")
  
  df$startMonth<-format(df$startDate_full,"%m")
  df$startYear<-format(df$startDate_full,"%Y")
  df$startDate<- as.Date(format(df$startDate_full,"%Y-%m-%d"))
  df$startDayofweek <-wday(df$startDate_full, label=TRUE, abbr=FALSE)
  df$startHour <-format(df$startDate_full,"%H")
  
  df <- df %>%
    mutate(
      sourceName = as.character(sourceName),
      sourceName = if_else(
        sourceName == "James work phone","iPhone",sourceName
      ),
      sourceName = if_else(
        grepl("Watch",sourceName),"iWatch",sourceName
      )
    )
  
  str(df)
  
  table(df$type)
```

# sleep

```{r}
df_sleep <- df %>%
  filter(
    type == 'HKCategoryTypeIdentifierSleepAnalysis' & 
      sourceName == "Misfit") %>%
  mutate(
    time = as.numeric(difftime(endDate_full, startDate_full), unit = "hours")
  ) %>%
  select(
    sourceName, startDate, endDate, startDate_full:time
  )

# does sleep start before midday or after?
  df_sleep <- df_sleep %>%
    mutate(
      sleep_day = case_when(
        as.numeric(.$startHour) >= 12 ~ "Today",
        TRUE ~ "Yesterday"
      )
    )
  
# total sleep
  df_sleep <- df_sleep %>%
    group_by(startDate, sleep_day) %>%
    summarise(
      time = sum(time),
      # min if today, max if yesterday
      temp_min = min(startDate_full),
      temp_max = max(endDate_full)
    ) 
  
  # move sleep midnight to midday to day before
  df_sleep <- df_sleep %>% ungroup %>%
    mutate(
      sleep_day_recode = case_when(
        .$sleep_day == "Yesterday" ~ "Today recoded",
        TRUE ~ "Today"
      ),
      startDate_recode = case_when(
        .$sleep_day == "Yesterday" ~ .$startDate - 1,
        TRUE ~ .$startDate
      )
    )
  
  # summarise
  df_sleep <- df_sleep %>%
    group_by(startDate_recode) %>%
    summarise(
      time = sum(time),
      bedtime = min(temp_min),
      getup = max(temp_max)
    )
  
  # add days in US/EU and if weekday
  df_sleep <- df_sleep %>%
    mutate(
      # NZ
      region = if_else(
        (startDate_recode >= as.Date("2016-12-22") & 
           startDate_recode <= as.Date("2017-01-12")),
        "NZ","EU"
      ),
      region = if_else(
        # US
        (startDate_recode >= as.Date("2017-03-26") & 
           startDate_recode <= as.Date("2017-04-03")) |
          (startDate_recode >= as.Date("2017-06-18") & 
           startDate_recode <= as.Date("2017-06-24")),
        "US",region
      ),
      # weekday?
      weekday = wday(bedtime),
      workday = if_else(
        weekday > 1 & weekday < 7, "Workday","Weekend"
      )
    )
  
  

# # expand all days
#   df_sleep <- left_join(
#     data.frame(
#       startDate = as.Date(
#         min(df_sleep$startDate):max(df_sleep$startDate), 
#         origin = "1970-01-01"
#         )
#     ),
#     df_sleep,
#     by = "startDate"
#   )
  
```

# sleep plot

```{r overtime}
# over time
df_sleep %>%
  #print table steps by date by month by year
  ggplot(
    aes(x=startDate_recode, y=time, 
        colour = region,
        shape = workday
        )
    ) + 
  geom_point(alpha = 0.8) + 
  ggthemes::theme_hc() +
  labs(
    x = "Date",
    y = "Time sleeping",
    colour = "Where in the world?",
    title = "Hours slept each night",
    subtitle = "based on data collected from my misfit",
    shape = "Weekday?"
    ) 
  
# hist by region and workday
df_sleep %>%
  # EU only
  filter(region == "EU") %>%
  ggplot(
    aes(x=time, fill = workday)
    ) + 
  geom_histogram(
    binwidth = 1,
    alpha = 0.8, position = "dodge"
    ) + 
  ggthemes::theme_hc() +
  facet_grid(workday ~ .) +
  labs(
    x = "Hours slept",
    y = "Count",
    title = "Hours slept each night",
    subtitle = "filtered to data nights spent in Europe",
    fill = "Weekday?"
    )  

```

```{r heatmapv1}
# heat map when asleep
  temp_sleep <- df_sleep %>%
    # EU only
    filter(region == "EU") %>%
    mutate(
      weekday = wday(bedtime, label = TRUE),
      bedtime = as.numeric(format(bedtime,"%H")),
      getup = as.numeric(format(getup,"%H"))
      )
  
  temp_output <- data.frame(
    Hour = rep(1:24,7),
    Weekday = rep(unique(temp_sleep$weekday)),
    HoursSlept = 0
  ) %>%
    arrange(
      Weekday, Hour
    )
  
  #holder <- vector("numeric", nrow(temp_output))
  for(i in 1:nrow(temp_output)){
    temp_i <- temp_output[i,]
    # pre midnight
    temp_i_dat <- temp_sleep %>%
      filter(
        temp_i$Weekday == weekday &
          bedtime <= temp_i$Hour &
          # do not take if less than 12, as that means day before
          bedtime >= 12
      ) 
    temp_premidnight <- nrow(temp_i_dat)
    # post midnight 
    temp_i$Weekday_num <- as.numeric(temp_i$Weekday)
    temp_i$Weekday_num <- case_when(
      temp_i$Weekday_num == 7 ~ 1,
      TRUE ~ temp_i$Weekday_num + 1
    )
    temp_i_dat <- temp_sleep %>%
      mutate(
        weekday_num = as.numeric(weekday)
      ) %>%
      filter(
        temp_i$Weekday_num == weekday_num &
          temp_i$Hour <= getup
      ) 
    temp_postmidnight <- nrow(temp_i_dat)
    
    # apply
    temp_output[i,]$HoursSlept <- sum(temp_premidnight,temp_postmidnight)
  }
  


temp_output %>%
  ggplot(aes(x=Weekday, y=Hour, fill=HoursSlept)) + 
  geom_tile() + 
  scale_fill_continuous(labels = scales::comma, low = 'white', high = 'red') +
  theme_bw() + 
  #theme(panel.grid.major = element_blank()) +
  ggthemes::theme_hc() +
  labs(
    x = "Day of the week",
    title = "When I'm asleep",
    subtitle = "heatmap showing time of day asleep",
    fill = "Count of times asleep at that hour"
    )  
```

try splitting by actual time overlap

```{r heatmapv2}

# time spent in each hour
  # function to calculate overlap post midnight
  jb_OverlapPost <- function(
    time = "01",
    start = "",
    end = "",
    date = ""
  ){
    output <- intersect(
          interval(start,end),
          interval(
            ymd_hms(
              paste0(
                as.character(date + 1),
                " ",time,":00:00"
                )
              ),
            ymd_hms(
              paste0(
                as.character(date + 1),
                " ",time,":59:00"
                )
              )
          )
        ) / dminutes(1)
    return(output)
  }
  # function to calculate overlap post midnight
  jb_OverlapPre <- function(
    time = "21",
    start = "",
    end = "",
    date = ""
  ){
    output <- intersect(
          interval(start,end),
          interval(
            ymd_hms(
              paste0(
                as.character(date),
                " ",time,":00:00"
                )
              ),
            ymd_hms(
              paste0(
                as.character(date),
                " ",time,":59:00"
                )
              )
          )
        ) / dminutes(1)
    return(output)
  }
    

  # run function
  temp_sleep <- df_sleep %>%
    filter(region == "EU") %>%
    mutate(
      # occurs after midnight (next day)
      int_24 = jb_OverlapPost("00",bedtime,getup,startDate_recode),
      int_01 = jb_OverlapPost("01",bedtime,getup,startDate_recode),
      int_02 = jb_OverlapPost("02",bedtime,getup,startDate_recode),
      int_03 = jb_OverlapPost("03",bedtime,getup,startDate_recode),
      int_04 = jb_OverlapPost("04",bedtime,getup,startDate_recode),
      int_05 = jb_OverlapPost("05",bedtime,getup,startDate_recode),
      int_06 = jb_OverlapPost("06",bedtime,getup,startDate_recode),
      int_07 = jb_OverlapPost("07",bedtime,getup,startDate_recode),
      int_08 = jb_OverlapPost("08",bedtime,getup,startDate_recode),
      int_09 = jb_OverlapPost("09",bedtime,getup,startDate_recode),
      int_10 = jb_OverlapPost("10",bedtime,getup,startDate_recode),
      int_11 = jb_OverlapPost("11",bedtime,getup,startDate_recode),
      # occurs after midnight (next day)
      int_12 = jb_OverlapPre("12",bedtime,getup,startDate_recode),
      int_13 = jb_OverlapPre("13",bedtime,getup,startDate_recode),
      int_14 = jb_OverlapPre("14",bedtime,getup,startDate_recode),
      int_15 = jb_OverlapPre("15",bedtime,getup,startDate_recode),
      int_16 = jb_OverlapPre("16",bedtime,getup,startDate_recode),
      int_17 = jb_OverlapPre("17",bedtime,getup,startDate_recode),
      int_18 = jb_OverlapPre("18",bedtime,getup,startDate_recode),
      int_19 = jb_OverlapPre("19",bedtime,getup,startDate_recode),
      int_20 = jb_OverlapPre("20",bedtime,getup,startDate_recode),
      int_21 = jb_OverlapPre("21",bedtime,getup,startDate_recode),
      int_22 = jb_OverlapPre("22",bedtime,getup,startDate_recode),
      int_23 = jb_OverlapPre("23",bedtime,getup,startDate_recode)
    ) %>%
    select(
      #bedtime,getup,
      startDate_recode,starts_with("int_")
    ) %>%
    # weekday
    mutate(
      weekday = wday(startDate_recode, label=TRUE, abbr=FALSE)
    ) %>% select(-startDate_recode) %>%
    # gather into long format
    tidyr::gather(
      timepoint,value,-weekday
    ) %>%
    # get totals
    group_by(weekday,timepoint) %>%
    summarise(
      total = sum(value, na.rm = TRUE)
    ) %>%
    # tidy
    mutate(
      Hour = as.numeric(gsub("[^0-9]","",timepoint))
    )
  
temp_sleep %>%
  ggplot(aes(x=weekday, y=Hour, fill=total)) + 
  geom_tile() + 
  scale_fill_continuous(labels = scales::comma, low = 'white', high = 'red') +
  theme_bw() + 
  #theme(panel.grid.major = element_blank()) +
  ggthemes::theme_hc() +
  theme(
    legend.position = "left"
  ) +
  labs(
    x = "Day of the week",
    title = "When I'm asleep",
    subtitle = "filtered to nights in the EU only",
    fill = "Total \nminutes \nasleep"
    )  
    
```

# steps

```{r}
df_steps <- df %>%
  filter(type == "HKQuantityTypeIdentifierStepCount") %>%
  select(
    -c(type,sourceVersion,unit,device)
  ) %>%
  mutate(
      # NZ
      region = if_else(
        (startDate >= as.Date("2016-12-22") & 
           startDate <= as.Date("2017-01-12")),
        "NZ","EU"
      ),
      region = if_else(
        # US
        (startDate >= as.Date("2017-03-26") & 
           startDate <= as.Date("2017-04-03")) |
          (startDate >= as.Date("2017-06-18") & 
           startDate <= as.Date("2017-06-24")),
        "US",region
      ),
      # weekday?
      weekday = wday(startDate_full),
      workday = if_else(
        weekday > 1 & weekday < 7, "Workday","Weekend"
      )
    )
  
# over time
df_steps %>%
  # summarise by day
  group_by(
    startDate,region,workday,sourceName
  ) %>%
  summarise(
    total = sum(value)
  ) %>%
  #print table steps by date by month by year
  ggplot(
    aes(x=startDate, y=total, 
        colour = region,
        shape = workday
        )
    ) + 
  geom_point(alpha = 0.8) + 
  ggthemes::theme_hc() +
  labs(
    x = "Date",
    y = "Total number of steps",
    colour = "Where in the world?",
    title = "Step counter totals",
    subtitle = "comparing three devices that count my steps",
    shape = "Weekday?"
    ) +
  facet_grid(sourceName ~ .)

```

```{r refiltersteps}
df_steps <- df_steps %>%
  filter(
    startDate > as.Date("2017-03-22")
  ) %>%
  # summarise by day
  group_by(
    startDate,region,workday,sourceName
  ) %>%
  summarise(
    total = sum(value)
  ) %>% ungroup()

```

```{r stepsFromApril}

df_steps %>%
  #print table steps by date by month by year
  ggplot(
    aes(x=startDate, y=total, 
        colour = sourceName, shape = sourceName
        )
    ) + 
  geom_point(alpha = 0.8) + 
  ggthemes::theme_hc() +
  labs(
    x = "Date",
    y = "Total number of steps",
    #colour = "Where in the world?",
    title = "Step counter totals",
    subtitle = "comparing three devices that count my steps"
    #shape = "Weekday?"
    ) +
  facet_grid(region ~ .)
```

In the ternery plot, all sides are weighted to sum to zero, so distance from the center represents the skew between the step count recorded by the Misfit, iWatch and iPhone.

```{r ternery}
library(ggtern)

ggtern(
  df_steps %>% 
    select(sourceName,startDate,total) %>%
    tidyr::spread(sourceName,total),
  aes(iPhone,iWatch,Misfit)
  ) + 
  # stat_density_tern(geom='polygon',
  #                       aes(fill=..level..),
  #                       base="identity",  ###NB Base Specification
  #                       colour='grey50') + 
  geom_point(colour = "red", alpha = 0.6, size = 3) + 
  theme_rgbw() + 
  theme_showarrows() + 
  #theme_legend_position('topleft') + 
  labs(title  = "Threeway comparison of daily step count",
       subtitle = "ternery plot showing skew in the data") + 
  geom_Tisoprop(value=0.5,colour='darkred', alpha = 0.5) + 
  geom_Lisoprop(value=0.5,colour='darkblue') + 
  geom_Risoprop(value=0.5,colour='darkgreen') +
  weight_percent()
```

Looks like there are two days I didn't wear the Misfit, so I will remove those two days.

```{r removenoweardays}
# days to delete
  df_steps %>%
    filter(total < 500) %>%
    .$startDate

df_steps <- df_steps %>%
  filter(
    !startDate %in% (df_steps %>%
      filter(total < 500) %>%
      .$startDate)
  )
```

Compare relative to misfit.

```{r modelsteps}

m_steps <- glm(
  total ~ region + workday + sourceName, 
  data = df_steps %>%
    mutate(
      sourceName = relevel(as.factor(sourceName), ref = "Misfit")
    )
)

# use the cluster.vcov function to get variance-covariance matrix
library(multiwayvcov)

temp <- as.data.frame(lmtest::coeftest(
  m_steps, 
  multiwayvcov::cluster.vcov(m_steps, df_steps$startDate)
  )[])

# make summary data
left_join(
    tibble(
      coef = names(coef(m_steps)),
      estimate = coef(m_steps)
      ),
    as.data.frame(confint(m_steps)) %>%
      mutate(
        coef = row.names(.)
        ),
    by = "coef"
  ) %>%
  mutate(
    # colour = ifelse(
    #   .$coef == "sourceNameiWatch" |
    #     .$coef == "sourceNameiPhone",
    #   "blue","black"
    # ),
    coef = case_when(
      .$coef == "workdayWorkday" ~ "Workday (c.f. weekend)",
      .$coef == "sourceNameiWatch" ~ "iWatch (c.f. Misfit)",
      .$coef == "sourceNameiPhone" ~ "iPhone (c.f. Misfit)",
      .$coef == "regionUS" ~ "In the US (c.f. in Europe)",
      TRUE ~ "Model intercept"
    )
  ) %>%
  ggplot() +
    geom_pointrange(
      aes(
        x = coef, 
        y = estimate, 
        ymin = `2.5 %`, 
        ymax = `97.5 %`
        )
    ) +
    geom_label(
      aes(
        x = coef, 
        y = estimate,
        label = round(estimate)
      )
    ) +
    ggthemes::theme_hc() +
    coord_flip() +
    geom_hline(
      aes(yintercept=0), colour = "red", linetype="dotted"
      ) +
    labs(
      x = "",
      y = "Daily step count"
    ) +
  theme(
    panel.grid.major.y = element_blank()
  )
  
  
```

# others plots

```{r}
df %>%
  filter(type == 'HKQuantityTypeIdentifierStepCount') %>%
  group_by(startYear,startMonth) %>%
  summarize(steps=sum(value)) %>%
  #print table steps by startMonth by startYear
  print (n=100) %>%
  #graph data by startMonth by startYear
  ggplot(aes(x=startMonth, y=steps, fill=startYear)) + 
  geom_bar(position='dodge', stat='identity') +
  scale_y_continuous(labels = scales::comma) +
  scale_fill_brewer() +
  theme_bw() +  
  theme(panel.grid.major = element_blank())

#boxplot data by startMonth by startYear
df %>%
  filter(type == 'HKQuantityTypeIdentifierStepCount') %>%
  group_by(startDate,startMonth,startYear) %>%
  summarize(steps=sum(value)) %>%
  #print table steps by startDate by startMonth by startYear
  print (n=100) %>%
  ggplot(aes(x=startMonth, y=steps)) + 
  geom_boxplot(aes(fill=(startYear))) + 
  scale_fill_brewer() +
  theme_bw() +  
  theme(panel.grid.major = element_blank())

#summary statistics by startMonth 
df %>%
  filter(type == 'HKQuantityTypeIdentifierStepCount') %>%
  group_by(startDate,startMonth,startYear) %>%
  summarize(steps=sum(value)) %>%
  #filter(startYear==2015) %>%
  group_by(startMonth) %>%
  summarize(mean = round(mean(steps), 2), sd = round(sd(steps), 2), 
            median = round(median(steps), 2), max = round(max(steps), 2), 
            min = round(min(steps), 2),`25%`= quantile(steps, probs=0.25),
            `75%`= quantile(steps, probs=0.75))

#boxplot data by day of week startYear
df %>%
  filter(type == 'HKQuantityTypeIdentifierStepCount') %>%
  group_by(startDayofweek,startDate,startYear) %>%
  summarize(steps=sum(value)) %>%
  #print table steps by startDate by startMonth by startYear
  print (n=100) %>%
  ggplot(aes(x=startDayofweek, y=steps)) + 
  geom_boxplot(aes(fill=(startYear))) + 
  scale_fill_brewer() +
  theme_bw() +  
  theme(panel.grid.major = element_blank())


#summary statistics by day of week for 2015
df %>%
  filter(type == 'HKQuantityTypeIdentifierStepCount') %>%
  group_by(startDayofweek,startDate,startYear) %>%
  summarize(steps=sum(value)) %>%
  #filter(startYear==2015) %>%
  group_by(startDayofweek) %>%
  summarize(mean = round(mean(steps), 2), sd = round(sd(steps), 2), 
            median = round(median(steps), 2), max = round(max(steps), 2), 
            min = round(min(steps), 2),`25%`= quantile(steps, probs=0.25),
            `75%`= quantile(steps, probs=0.75)) %>%
  arrange(desc(median))

#heatmap day of week hour of day
df %>%
  filter(type == 'HKQuantityTypeIdentifierStepCount') %>%
  group_by(startDate,startDayofweek,startHour) %>% 
  summarize(steps=sum(value)) %>% 
  group_by(startHour,startDayofweek) %>% 
  summarize(steps=sum(steps)) %>% 
  arrange(desc(steps)) %>%
  #print table steps by startDate by startMonth by startYear
  print (n=100) %>%
  ggplot(aes(x=startDayofweek, y=startHour, fill=steps)) + 
  geom_tile() + 
  scale_fill_continuous(labels = scales::comma, low = 'white', high = 'red') +
  theme_bw() + 
  theme(panel.grid.major = element_blank())
```